server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/msmkdxx/test.git
          searchPaths: config
          force-pull: true
      label: master
